### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by Security-Champions-Beta** [solo10010/solo-nuclei-templates#1]
How can I run this template?
https://github.com/solo10010/solo-nuclei-templates/blob/main/Configuration-Files/codeigniter-env-1.yaml

**Comment by solo10010** [comment]
Good afternoon, I didn’t think that anyone would use this so quickly, I collect and mix these templates from more than 40 other repositories.

Templates by this author do not work yet. Please refrain from using the repository, I will make it non-public until all templates work properly.

**Comment by solo10010** [comment]
These templates you are running are taken from https://github.com/0xAwali/Virtual-Host
